Update Slab Preset
bridge-core/editor-packages pull request #10
Opened 2021-11-03 00:34 UTC by Chikorita-Lover

Updates the slab preset to allow placing on bottom faces and combining the top and bottom faces

2021-11-03 08:41 UTC, solvedDev requested changes
LGTM. Make sure to bump the extension version though so people can actually update to a version with the changes you've made :)

2021-11-03 08:42 UTC, solvedDev approved these changes
Oops 🙃

2021-11-03 17:13 UTC, Joelant05 requested changes
I've made some comments where there are some changes to be made. Since we have updated bridge. to respect the pack paths defined in the project config, we cannot assume the packs will be called "BP", "RP" etc. This change is supported in presets with the "packPath" property as a replacement for starting the destination path with "BP", "RP" etc.

2021-11-03 17:13 UTC, Joelant05 commented on packages/minecraftBedrock/preset/block/slab/manifest.json
> +			"BP/blocks/{{PRESET_PATH}}{{IDENTIFIER}}.json",
Remove "BP/"

2021-11-03 17:13 UTC, Joelant05 commented on packages/minecraftBedrock/preset/block/slab/manifest.json
> +			"BP/blocks/{{PRESET_PATH}}double_{{IDENTIFIER}}.json",
Remove "BP/"

2021-11-03 17:13 UTC, Joelant05 commented on packages/minecraftBedrock/preset/block/slab/manifest.json
> +			"BP/loot_tables/blocks/double_{{IDENTIFIER}}.json",
Remove "BP/"

2021-11-03 17:13 UTC, Joelant05 commented on packages/minecraftBedrock/preset/block/slab/manifest.json
> +			"RP/models/blocks/slab.geo.json",
Remove "RP/"

2021-11-03 17:13 UTC, Joelant05 commented on packages/minecraftBedrock/preset/block/slab/manifest.json
> +			"RP/blocks.json",
Remove "RP/"

2021-11-03 17:13 UTC, Joelant05 commented on packages/minecraftBedrock/preset/block/slab/manifest.json
> +			"RP/texts/en_US.lang",
Remove "RP/"

2021-11-03 22:04 UTC, Chikorita-Lover commented
Okay, I've gone and changed those. They weren't working as intended when I was testing the preset, and instead saved the files in the project's base folder.

2021-11-03 22:22 UTC, Joelant05 commented
Were you testing them on the latest dev build?

2021-11-03 22:25 UTC, Chikorita-Lover commented
No, I tested it on the latest stable release (2.1.5).

2021-11-04 07:10 UTC, Joelant05 commented
Ah ok, that's why then. We've only recently made these changes on the dev build. This looks good to merge now.

2021-11-04 07:11 UTC, Joelant05 approved these changes

2021-11-04 07:11 UTC, merged