Update data to 1.20.10 (Preview)
bridge-core/editor-packages pull request #39
Opened 2023-06-27 21:29 UTC by outercloudstudio

2023-06-27 23:05 UTC, NguyenDuck commented
Remove tracking the `dist` folder and `.lock` file, so thats will auto-generated, dont need tracked thats change

2023-06-27 23:06 UTC, outercloudstudio commented
I'll add that to the gitnore

2023-06-27 23:08 UTC, NguyenDuck commented
And deleted also 💯

2023-06-28 00:21 UTC, NguyenDuck commented
Block Traits completed as #40

2023-06-28 00:55 UTC, ThomasOrs commented
Block traits are brand new in experimental, the functionality can be seen here https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blocktraits

2023-06-28 00:56 UTC, outercloudstudio commented
Yep I'm polishing up NguyenDuck's commit for block traits right now.

2023-06-28 01:13 UTC, ThomasOrs commented
To ensure everyone has the same dependencies, lock files should be committed to version control.
Adding the deno.lock file to gitignore is beyond the scope of this pull request.

2023-06-28 21:12 UTC, outercloudstudio commented
There are some changes I need to complete before this is ready. Please hold off on the review.

2023-06-30 02:14 UTC, NguyenDuck commented
* `minecraft:rotation` is deprecated in 1.19.80

2023-06-30 02:15 UTC, outercloudstudio commented
> * `minecraft:rotation` is deprecated in 1.19.80

Can you link the change log that say this? I can't find it on the 1.19.80 release change log.

2023-06-30 02:29 UTC, NguyenDuck commented
> Can you link the change log that say this? I can't find it on the 1.19.80 release change log.

The change log doesn't say that, but it's thrown error on used in minecraft

2023-06-30 02:30 UTC, outercloudstudio commented
Alright thanks for catching that. I'll fix it now.

2023-06-30 18:06 UTC, ThomasOrs commented
@outercloudstudio it was deprecated in favour of transformation
https://learn.microsoft.com/en-us/minecraft/creator/documents/update1.19.80
> [transformation](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_transformation) - replaces the previous block rotation component (and adds scaling and translation)

https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_transformation

2023-07-04 19:19 UTC, ThomasOrs requested changes

2023-07-04 19:19 UTC, ThomasOrs commented on packages/minecraftBedrock/schema/block/v1.19.80/components/part_visibility.json
> +	"deprecationMessage": "Deprecated as of v1.19.80 - Sets conditions for when the block's different parts are visible."
This should point users to use `bone_visiblity`

2023-07-04 19:19 UTC, ThomasOrs commented on packages/minecraftBedrock/schema/block/v1.19.80/components/rotation.json
> +	"deprecationMessage": "Deprecated as of v1.19.80 - The block's rotation around the center of the cube in degrees. The rotation is specified as [x, y, z]. Angles need to be in factors of 90."
This should point users to use `transformation`

2023-07-04 19:34 UTC, ThomasOrs commented on packages/minecraftBedrock/schema/block/v1.19.80/components/part_visibility.json
> +	"deprecationMessage": "Deprecated as of v1.19.80 - Sets conditions for when the block's different parts are visible."
Resolved in c7bc99d6f7eafb48496267af0aee1ef2362a84c8

2023-07-04 19:34 UTC, ThomasOrs approved these changes

2023-07-04 20:30 UTC, merged