upd: removed tracking auto-generated files and vscode settings
bridge-core/editor-packages pull request #42
Opened 2023-06-28 07:59 UTC by NguyenDuck

`dist` folder very conflict on merge
`deno.lock` file generated depend on `deno.json`
vscode setting `editor.formatOnSave` make the json files break, inline json array or space at start, end of array items

Not format
```jsonc
{
    "array_name": ["item1", "item2"]
}
```

Formated
```jsonc
{
    "array_name": [
        "item1",
        "item2"
    ]
}
```

Formated ( `json.format.keepLines` enabled )
```jsonc
{
    "array_name": [ "item1", "item2" ]
}
```

2023-06-28 13:39 UTC, ThomasOrs requested changes
See comments

2023-06-28 13:39 UTC, ThomasOrs commented on deno.lock
Lock files are important in open-source projects to ensure consistent versioning between users.

2023-06-28 13:39 UTC, ThomasOrs commented on .gitignore
> +deno.lock
Lock files are important in open-source projects to ensure consistent versioning between users.

2023-06-28 23:16 UTC, outercloudstudio commented
Deno.lock can not be used with this project as this project uses sky pack which appears to change the hash of the dependencies without control preventing the lock file from being useful.

2023-06-29 21:32 UTC, outercloudstudio commented
Closing this without merging since the only changes needed from this is fixing dist folder conflict. The other changes should not be made.

2023-06-29 21:32 UTC, closed without merging